language: R
sudo: required
cache: packages
warnings_are_errors: false

r:
  - release
  - devel

r_packages:
  - devtools
  - covr

r_github_packages:
  - johndharrison/binman
  - johndharrison/wdman
  - ropensci/RSelenium
  
after_success:
- Rscript -e 'covr::codecov()'